dist: xenial
services:
  - mongodb
language: python
matrix:
  include:
    - python: "2.7"
    - python: "3.4"
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"
  allow_failures:
    - python: "3.7"
install:
  - "pip install ."
  - pip install coveralls
script: coverage run --source=flask_potion setup.py test
after_success:
    - coveralls
